spring:
  application:
    name: mipt-mts-homework
  datasource:
    url: jdbc:postgresql://localhost:5432/kruase
    username: kruase
    password: kruase-password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: shutdown
      base-path: /admin

server:
  tomcat:
    threads:
      min-spare: 10
      max: 200

resilience4j:
  ratelimiter:
    instances:
      # noinspection SpringBootApplicationYaml
      api:
        limitForPeriod: 5
        limitRefreshPeriod: 10s
        timeoutDuration: 0
  circuitbreaker:
    instances:
      # noinspection SpringBootApplicationYaml
      api:
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: count_based
        slidingWindowSize: 10

cache:
  expire-after-seconds: 300
  initial-capacity: 100
  maximum-size: 100
